### ISSUE TITLE
Namron Thermostat misinterpreted 

### ISSUE THREAD

**Issue by arnebenjamin** [gruijter/com.gruijter.zigbee2mqtt#27]
Namron thermostat is being misinterpreted by the app and created as an "Other" device type, resulting in only controls over the "child_lock" attribute in Homey. It doesn't help changing type to thermostat afterwards in regards to available controls. Is it possible to add support, or see how this should be filtered out in Zigbee2mqtt to make it function properly? Just filtering with filtered_attributes does not help.

Below are messages from the MQTT broker:

```
zigbee2mqtt/Walk-In Termostat gulv/
{
  "alarm_airtemp_overvalue": 27,
  "away_mode": "OFF",
  "button_vibration_level": "low",
  "child_lock": "UNLOCK",
  "current": 0,
  "display_auto_off_enabled": "disabled",
  "dry_time": 5,
  "energy": 1.4,
  "floor_sensor_calibration": 0,
  "floor_sensor_type": "10k",
  "hysterersis": 0.5,
  "lcd_brightness": "mid",
  "linkquality": 96,
  "local_temperature": 23.01,
  "local_temperature_calibration": 0,
  "mode_after_dry": "manual",
  "occupancy": true,
  "occupied_heating_setpoint": 23,
  "outdoor_temperature": 0,
  "power": 0,
  "powerup_status": "last_status",
  "running_state": "idle",
  "sensor": "air",
  "system_mode": "heat",
  "temperature_display": "room",
  "unoccupied_heating_setpoint": 6,
  "update": {
    "installed_version": 22,
    "latest_version": 22,
    "state": "idle"
  },
  "update_available": null,
  "voltage": 0,
  "window_open_check": 0
}
```

![image](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/30862757/a2bc247e-e6c0-46b1-8b10-935fc42a3512)

![image](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/30862757/eb856977-d6d5-49d8-99aa-f8ab3cb4f914)

**Comment by gruijter** [comment]
**Why is my device not (fully) supported?**
The current version supports basic devices like window/door contacts, power plugs, thermostats, basic lights and basic sensors.
Do know that I mainly built this app for my own use, but I added generic device mapping so that others can enjoy it too. At this time I do not intend to put an extreme amount of effort in adding support for more devices. If you are a programmer you are more than welcome to do a pull request on Github. But to really add a device to the Homey app, I need to have my hands on it and tinker around with it. So, if you are willing to donate the device, I am willing to put in the extra effort to integrate it. When you want to donate a device, send me the funds to buy one (including shipping to NL).

Donate
Feel free to donate the funds of a device you like to have integrated, or buy me some beers for the hard work I have already put in :wink:

https://www.paypal.com/paypalme/gruijter


[PayPal.Me](https://www.paypal.com/paypalme/gruijter)

[Pay Robin de Gruijter using PayPal.Me 12](https://www.paypal.com/paypalme/gruijter)
Go to paypal.me/gruijter and type in the amount. Since it’s PayPal, it's easy and
